<?php
namespace app\index\controller;
use think\Controller;
class Index extends Controller
{
    protected $member_info;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $param = input('get.');
        if(isset($param['token'])){
            $token_info = model('MemberToken')->with('member')->where(['token' => $param['token']])->find();
            $token_info = $token_info->toArray();
            $this->member_info = $token_info['member'];
        }
    }

    public function index()
    {
        //$this->redirect(url('Admin/index/index'));
        return $this->fetch();
    }
    public function order()
    {
        return $this->fetch();
    }
    public function center(){
        return $this->fetch();
    }
    public function menu(){
        $this->assign('uid',$this->member_info['member_id']);
        return $this->fetch();
    }
    public function detail(){
        $this->assign('uid',$this->member_info['member_id']);
        $mid = input('get.mid');
        $this->assign('mid',$mid);
        return $this->fetch();
    }
}
