<?php
namespace app\index\controller;
use think\Controller;
class Index extends Controller
{
    protected $member_info;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->redirect(url('Admin/index/index'));
    }
}
